- name: Build
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-files
          path: dist/ # أو غيرها إذا كان مجلد المخرجات عندك باسم مختلف (مثل build أو public)
