name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install and Build
        run: |
          pnpm install
          pnpm run build
          env:
            TSC_COMPILE_ON_ERROR: 'true'
            CI: 'false'
      # هذا السطر الجديد هو الذي سيظهر لك زر التحميل (Artifact)
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: game-files
          path: dist/ # أو مجلد البناء الخاص بك (قد يكون build أو public)
